package de.fgna.pocketdev.diagnostics

import de.fgna.pocketdev.project.ProjectConfig
import de.fgna.pocketdev.ssh.CommandUiState

data class DiagnosticIssueDraft(
    val title: String,
    val body: String,
)

object DiagnosticDraftBuilder {
    private const val MAX_OUTPUT_CHARS = 6000
    private val secretAssignment = Regex(
        pattern = "(?i)\\b(password|passwd|token|secret|api[_-]?key)\\b(\\s*[=:]\\s*)([^\\s'\\\"]+|['\\\"][^'\\\"]*['\\\"])",
    )

    fun build(project: ProjectConfig, command: CommandUiState): DiagnosticIssueDraft {
        val exitCode = requireNotNull(command.exitCode) { "A diagnostic draft requires a completed command." }
        require(exitCode != 0) { "A diagnostic draft is only available for failed commands." }

        val safeCommand = redact(command.command.trim())
        val rawOutput = command.combinedOutput.trim()
        val boundedOutput = if (rawOutput.length <= MAX_OUTPUT_CHARS) {
            rawOutput
        } else {
            "[output truncated to last $MAX_OUTPUT_CHARS characters]\n" + rawOutput.takeLast(MAX_OUTPUT_CHARS)
        }
        val safeOutput = redact(boundedOutput).replace("```", "``\u200B`")

        val title = "[${project.name}] Command failed (exit $exitCode)"
        val body = buildString {
            appendLine("## Failure")
            appendLine()
            appendLine("Project: `${project.name}`")
            appendLine("Exit code: `$exitCode`")
            appendLine()
            appendLine("## Command")
            appendLine()
            appendLine("```sh")
            appendLine(safeCommand)
            appendLine("```")
            appendLine()
            appendLine("## Output")
            appendLine()
            appendLine("```text")
            appendLine(safeOutput.ifBlank { "(no output)" })
            appendLine("```")
            appendLine()
            appendLine("---")
            append("Generated by PocketDev. Review and edit before submitting.")
        }
        return DiagnosticIssueDraft(title = title, body = body)
    }

    internal fun redact(value: String): String = secretAssignment.replace(value) { match ->
        "${match.groupValues[1]}${match.groupValues[2]}<redacted>"
    }
}
